# Generated by Django 4.1.3 on 2023-01-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='order_id',
        ),
    ]
