# Generated by Django 4.1.3 on 2023-07-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_customuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default='profilepic.png', upload_to='profilepic'),
        ),
    ]
