# Generated by Django 4.1.3 on 2023-01-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_remove_customuser_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credit_points',
            field=models.IntegerField(default=0),
        ),
    ]
