# Generated by Django 4.1.3 on 2023-04-12 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuitionmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition_unlock',
            name='unlock_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
