# Generated by Django 4.1.3 on 2023-04-14 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuitionmanager', '0002_tuition_unlock_unlock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitions',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tuitions',
            name='posted_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
