# Generated by Django 4.1.3 on 2023-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
