# Generated by Django 4.1.3 on 2023-02-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_plan_plan_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='orders',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.plan'),
        ),
    ]
